#!/usr/bin/perl
#
# This file is part of Pod-Markdown
#
# This software is copyright (c) 2011 by Randy Stauner.
#
# This is free software; you can redistribute it and/or modify it under
# the same terms as the Perl 5 programming language system itself.
#
use 5.008;
use strict;
use warnings;
# PODNAME: pod2markdown
# ABSTRACT: Convert POD text to Markdown

my $debuglevel = 9;
use Pod::Simple::Debug (\$debuglevel, 0);
use Pod::Simple::HTML;
use FindBin;
use File::Find;
use File::Path qw(make_path remove_tree);
use File::Basename;
use Data::Dumper;
use URI::Escape;

my %opts = (
  output_encoding => 'UTF-8',
  perldoc_url_prefix => './',
);

my $outdir = "$FindBin::Bin/../pod";
my $indir  = "$FindBin::Bin/../lib/";

my %files;
my %podhtml_LOT;

find({wanted => sub {
  
  if ( $File::Find::name =~ m#$indir([^.].*)[.](pm|pod)# ) {
    my $p = $1;
    my $f = "$1.$2";
    $p =~ s#/#::#g;
    $files{$p} = $f;
    my $h = uri_escape($p);
    $podhtml_LOT{$p} = "./$h.html";
}}}, $indir);

remove_tree($outdir);

while (my ($package, $file) = each %files) {
  my $of = "$outdir/$package.html";
  my $od = dirname($of);
  -d $od || make_path($od);

  convert("$indir/$file", $of);
}

exit 0;

sub convert {
    my ($in_file, $out_file) = @_;
    my $p = Pod::Simple::HTML->new;
    $p->{podhtml_LOT} = \%podhtml_LOT;
    my $html;
    $p->output_string(\$html);
    $p->parse_file($in_file);
    if ($html) {
      print "$out_file\n";
      my $of;
      open($of, '>', $out_file) || die "Could not open $of: $!\n";
      binmode $of, ':bytes';
      print $of $html;
      close $of;
    }
}

__END__
