#!/usr/bin/perl
#
# This file is part of Pod-Markdown
#
# This software is copyright (c) 2011 by Randy Stauner.
#
# This is free software; you can redistribute it and/or modify it under
# the same terms as the Perl 5 programming language system itself.
#
use 5.008;
use strict;
use warnings;
# PODNAME: pod2markdown
# ABSTRACT: Convert POD text to Markdown

use Pod::Markdown;
use FindBin;
use File::Find;
use File::Path qw(make_path);
use File::Basename;
use Data::Dumper;

my %opts = (
  output_encoding => 'UTF-8',
  perldoc_url_prefix => './',
);

my $outdir = "$FindBin::Bin/../pod_md";
my $indir  = "$FindBin::Bin/../lib/";

my %files;
find({wanted => sub {
  
  if ( $File::Find::name =~ m#$indir([^.].*)[.](pm|pod)# ) {
    my $p = $1;
    my $f = "$1.$2";
    $p =~ s#/#::#g;
    $files{$p} = $f;
}}}, $indir);

while (my ($package, $file) = each %files) {
  my $of = "$outdir/$package.md";
  my $od = dirname($of);
  -d $od || make_path($od);

  convert("$indir/$file", $of);
}

exit 0;

sub convert {
    my ($in_file, $out_file) = @_;
    my $parser = Pod::Markdown->new(%opts);
    my $md;
    # $parser->output_fh($out_file);
    $parser->output_string(\$md);
    $parser->parse_file($in_file);
    if ($md ne "\n") {
      print "$out_file\n";
      my $of;
      open($of, '>', $out_file) || die "Could not open $of: $!\n";
      binmode $of, ':bytes';
      print $of $md;
      close $of;
    }
}

__END__
